CREATE TABLE [dbo].[SystemUser] (
    [SystemUserId]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [UserName]                NVARCHAR (50)  NOT NULL,
    [Password]                NVARCHAR (MAX) NOT NULL,
    [Email]                   NVARCHAR (50)  NOT NULL,
    [Level]                   INT            CONSTRAINT [DF_SystemUser_Level] DEFAULT ((99999)) NOT NULL,
    [Comments]                NVARCHAR (MAX) NULL,
    [Idnp]                    BIGINT         NOT NULL,
    [FirstName]               NVARCHAR (100) NOT NULL,
    [Surname]                 NVARCHAR (100) NOT NULL,
    [MiddleName]              NVARCHAR (100) NULL,
    [DateOfBirth]             DATETIME       NOT NULL,
    [Gender]                  INT            NOT NULL,
    [PasswordQuestion]        NVARCHAR (100) NULL,
    [PasswordAnswer]          NVARCHAR (100) NULL,
    [IsApproved]              BIT            CONSTRAINT [DF_SystemUser_IsApproved] DEFAULT ((0)) NOT NULL,
    [IsOnLine]                BIT            CONSTRAINT [DF_SystemUser_IsOnLine] DEFAULT ((0)) NOT NULL,
    [IsLockedOut]             BIT            CONSTRAINT [DF_SystemUser_IsLockedOut] DEFAULT ((0)) NOT NULL,
    [CreationDate]            DATETIME       NOT NULL,
    [LastActivityDate]        DATETIME       NOT NULL,
    [LastPasswordChangedDate] DATETIME       NOT NULL,
    [LastLockoutDate]         DATETIME       NOT NULL,
    [FailedAttemptStart]      DATETIME       NOT NULL,
    [FailedAnswerStart]       DATETIME       NOT NULL,
    [FailedAttemptCount]      INT            CONSTRAINT [DF_SystemUser_FailedAttemptCount] DEFAULT ((0)) NOT NULL,
    [FailedAnswerCount]       INT            CONSTRAINT [DF_SystemUser_FailedAnswerCount] DEFAULT ((0)) NOT NULL,
    [LastLoginDate]           DATETIME       NOT NULL,
    [LastUpdateDate]          DATETIME       NOT NULL,
    [Language]                NVARCHAR (100) NULL,
    [MobileNumber]            NVARCHAR (20)  NULL,
    [ContactName]             NVARCHAR (100) NULL,
    [ContactMobileNumber]     NVARCHAR (20)  NULL,
    [StreetAddress]           NVARCHAR (100) NULL,
    [ElectionId]              BIGINT         CONSTRAINT [DF_SystemUser_ElectionId] DEFAULT ((-2)) NULL,
    [RegionId]                BIGINT         CONSTRAINT [DF_SystemUser_RegionId] DEFAULT ((-2)) NULL,
    [PollingStationId]        BIGINT         CONSTRAINT [DF_SystemUser_PollingStationId] DEFAULT ((-2)) NULL,
    [CircumscriptionId]       BIGINT         CONSTRAINT [DF_SystemUser_CircumscriptionId] DEFAULT ((-2)) NULL,
    [EditUserId]              BIGINT         CONSTRAINT [DF_SystemUser_EditUserId] DEFAULT ((1)) NOT NULL,
    [EditDate]                DATETIME       CONSTRAINT [DF_SystemUser_EditDate] DEFAULT (sysdatetime()) NOT NULL,
    [Version]                 INT            CONSTRAINT [DF_SystemUser_Version] DEFAULT ((1)) NOT NULL,
    [IsDeleted]               BIT            CONSTRAINT [DF_SystemUser_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SystemUser_1] PRIMARY KEY CLUSTERED ([SystemUserId] ASC) WITH (FILLFACTOR = 80)
);

