<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="password.services.soap.rpc.framework.server.registru.md" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="password.services.soap.rpc.framework.server.registru.md" xmlns:intf="password.services.soap.rpc.framework.server.registru.md" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="changeMyPasswordRequest">

      <wsdl:part name="newPasswordHash" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="changeMyPasswordResponse">

   </wsdl:message>

   <wsdl:portType name="Password">

      <wsdl:operation name="changeMyPassword" parameterOrder="newPasswordHash">

         <wsdl:input message="impl:changeMyPasswordRequest" name="changeMyPasswordRequest"/>

         <wsdl:output message="impl:changeMyPasswordResponse" name="changeMyPasswordResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="passwordSoapBinding" type="impl:Password">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="changeMyPassword">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="changeMyPasswordRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="password.services.soap.rpc.framework.server.registru.md" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="changeMyPasswordResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="password.services.soap.rpc.framework.server.registru.md" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="PasswordService">

      <wsdl:port binding="impl:passwordSoapBinding" name="password">

         <wsdlsoap:address location="http://alice:9001/password/services/password"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
