//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP.CEC.WebClient.RspCecService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="cec.services.soap.rpc.framework.server.registru.md", ConfigurationName="RspCecService.Cec")]
    public interface Cec {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistrationData))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getChangedPhysicalPersonListReturn")]
        RSP.CEC.WebClient.RspCecService.IdnpRequestData getChangedPhysicalPersonList();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getChangedPhysicalPersonListReturn")]
        System.Threading.Tasks.Task<RSP.CEC.WebClient.RspCecService.IdnpRequestData> getChangedPhysicalPersonListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistrationData))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getPhysicalPersonDataReturn")]
        RSP.CEC.WebClient.RspCecService.PhysicalPersonRequestData getPhysicalPersonData(long idnp);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getPhysicalPersonDataReturn")]
        System.Threading.Tasks.Task<RSP.CEC.WebClient.RspCecService.PhysicalPersonRequestData> getPhysicalPersonDataAsync(long idnp);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistrationData))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmReceivedPersonReturn")]
        RSP.CEC.WebClient.RspCecService.ResultData confirmReceivedPerson(long idnp);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmReceivedPersonReturn")]
        System.Threading.Tasks.Task<RSP.CEC.WebClient.RspCecService.ResultData> confirmReceivedPersonAsync(long idnp);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://cec.soap.rpc.framework.server.registru.md")]
    public partial class IdnpRequestData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long[] idnpField;
        
        private ResultData resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public long[] idnp {
            get {
                return this.idnpField;
            }
            set {
                this.idnpField = value;
                this.RaisePropertyChanged("idnp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ResultData result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://cec.soap.rpc.framework.server.registru.md")]
    public partial class ResultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorTextField;
        
        private System.Nullable<int> resultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("errorText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://cec.soap.rpc.framework.server.registru.md")]
    public partial class AddressData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> administrativCodeField;
        
        private string blockField;
        
        private string flatField;
        
        private string houseField;
        
        private string localityField;
        
        private string regionField;
        
        private string streetField;
        
        private System.Nullable<int> streetCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> administrativCode {
            get {
                return this.administrativCodeField;
            }
            set {
                this.administrativCodeField = value;
                this.RaisePropertyChanged("administrativCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string block {
            get {
                return this.blockField;
            }
            set {
                this.blockField = value;
                this.RaisePropertyChanged("block");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string flat {
            get {
                return this.flatField;
            }
            set {
                this.flatField = value;
                this.RaisePropertyChanged("flat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string house {
            get {
                return this.houseField;
            }
            set {
                this.houseField = value;
                this.RaisePropertyChanged("house");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
                this.RaisePropertyChanged("locality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> streetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
                this.RaisePropertyChanged("streetCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://cec.soap.rpc.framework.server.registru.md")]
    public partial class RegistrationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressData addressField;
        
        private System.Nullable<System.DateTime> expirationDateField;
        
        private System.Nullable<System.DateTime> regDateField;
        
        private System.Nullable<int> regTypeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public AddressData address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("expirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> regDate {
            get {
                return this.regDateField;
            }
            set {
                this.regDateField = value;
                this.RaisePropertyChanged("regDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> regTypeCode {
            get {
                return this.regTypeCodeField;
            }
            set {
                this.regTypeCodeField = value;
                this.RaisePropertyChanged("regTypeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://cec.soap.rpc.framework.server.registru.md")]
    public partial class DocumentData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> docTypeCodeField;
        
        private System.Nullable<System.DateTime> expirationDateField;
        
        private System.Nullable<System.DateTime> issueDateField;
        
        private string issueLocationField;
        
        private string numberField;
        
        private string seriesField;
        
        private System.Nullable<bool> validityField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> docTypeCode {
            get {
                return this.docTypeCodeField;
            }
            set {
                this.docTypeCodeField = value;
                this.RaisePropertyChanged("docTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("expirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("issueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string issueLocation {
            get {
                return this.issueLocationField;
            }
            set {
                this.issueLocationField = value;
                this.RaisePropertyChanged("issueLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
                this.RaisePropertyChanged("series");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> validity {
            get {
                return this.validityField;
            }
            set {
                this.validityField = value;
                this.RaisePropertyChanged("validity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://cec.soap.rpc.framework.server.registru.md")]
    public partial class PhysicalPersonData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private System.Nullable<bool> citizenRMField;
        
        private System.Nullable<bool> deadField;
        
        private string firstNameField;
        
        private DocumentData identDocumentField;
        
        private System.Nullable<long> idnpField;
        
        private string lastNameField;
        
        private RegistrationData[] registrationField;
        
        private string secondNameField;
        
        private System.Nullable<short> sexCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> citizenRM {
            get {
                return this.citizenRMField;
            }
            set {
                this.citizenRMField = value;
                this.RaisePropertyChanged("citizenRM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> dead {
            get {
                return this.deadField;
            }
            set {
                this.deadField = value;
                this.RaisePropertyChanged("dead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public DocumentData identDocument {
            get {
                return this.identDocumentField;
            }
            set {
                this.identDocumentField = value;
                this.RaisePropertyChanged("identDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> idnp {
            get {
                return this.idnpField;
            }
            set {
                this.idnpField = value;
                this.RaisePropertyChanged("idnp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RegistrationData[] registration {
            get {
                return this.registrationField;
            }
            set {
                this.registrationField = value;
                this.RaisePropertyChanged("registration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string secondName {
            get {
                return this.secondNameField;
            }
            set {
                this.secondNameField = value;
                this.RaisePropertyChanged("secondName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<short> sexCode {
            get {
                return this.sexCodeField;
            }
            set {
                this.sexCodeField = value;
                this.RaisePropertyChanged("sexCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://cec.soap.rpc.framework.server.registru.md")]
    public partial class PhysicalPersonRequestData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PhysicalPersonData personField;
        
        private ResultData resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PhysicalPersonData person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
                this.RaisePropertyChanged("person");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ResultData result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CecChannel : RSP.CEC.WebClient.RspCecService.Cec, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CecClient : System.ServiceModel.ClientBase<RSP.CEC.WebClient.RspCecService.Cec>, RSP.CEC.WebClient.RspCecService.Cec {
        
        public CecClient() {
        }
        
        public CecClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CecClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CecClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CecClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RSP.CEC.WebClient.RspCecService.IdnpRequestData getChangedPhysicalPersonList() {
            return base.Channel.getChangedPhysicalPersonList();
        }
        
        public System.Threading.Tasks.Task<RSP.CEC.WebClient.RspCecService.IdnpRequestData> getChangedPhysicalPersonListAsync() {
            return base.Channel.getChangedPhysicalPersonListAsync();
        }
        
        public RSP.CEC.WebClient.RspCecService.PhysicalPersonRequestData getPhysicalPersonData(long idnp) {
            return base.Channel.getPhysicalPersonData(idnp);
        }
        
        public System.Threading.Tasks.Task<RSP.CEC.WebClient.RspCecService.PhysicalPersonRequestData> getPhysicalPersonDataAsync(long idnp) {
            return base.Channel.getPhysicalPersonDataAsync(idnp);
        }
        
        public RSP.CEC.WebClient.RspCecService.ResultData confirmReceivedPerson(long idnp) {
            return base.Channel.confirmReceivedPerson(idnp);
        }
        
        public System.Threading.Tasks.Task<RSP.CEC.WebClient.RspCecService.ResultData> confirmReceivedPersonAsync(long idnp) {
            return base.Channel.confirmReceivedPersonAsync(idnp);
        }
    }
}
