CREATE TABLE [schematmp].[ElectionCompetitor] (
    [ElectionCompetitorId]      BIGINT          NOT NULL,
    [ElectionRoundId]           BIGINT          NOT NULL,
    [PoliticalPartyId]          BIGINT          NULL,
    [AssignedCircumscriptionId] BIGINT          NULL,
    [Code]                      NVARCHAR (100)  NOT NULL,
    [NameRo]                    NVARCHAR (MAX)  NOT NULL,
    [NameRu]                    NVARCHAR (MAX)  NOT NULL,
    [ColorLogo]                 VARBINARY (MAX) NULL,
    [DateOfRegistration]        DATETIME        NOT NULL,
    [Status]                    INT             NOT NULL,
    [IsIndependent]             BIT             NOT NULL,
    [BallotOrder]               INT             NOT NULL,
    [EditUserId]                BIGINT          NOT NULL,
    [EditDate]                  DATETIME        NOT NULL,
    [Version]                   INT             NOT NULL,
    [PartyOrder]                INT             NULL,
    [DisplayFromNameRo]         NVARCHAR (MAX)  NULL,
    [DisplayFromNameRu]         NVARCHAR (MAX)  NULL,
    [RegistryNumber]            INT             NULL,
    [BlackWhiteLogo]            VARBINARY (MAX) NULL,
    [PartyType]                 INT             NOT NULL,
    [BallotPaperNameRo]         NVARCHAR (MAX)  NULL,
    [BallotPaperNameRu]         NVARCHAR (MAX)  NULL,
    [BallotPapperCustomCssRo]   NCHAR (128)     NULL,
    [BallotPapperCustomCssRu]   NCHAR (128)     NULL,
    [Color]                     VARCHAR (6)     NULL,
    CONSTRAINT [PK_ElectionCompetitor] PRIMARY KEY CLUSTERED ([ElectionCompetitorId] ASC) WITH (FILLFACTOR = 80)
);

