//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEC.SAISE.EDayModule.EDayServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDayResponse", Namespace="http://schemas.datacontract.org/2004/07/SAISE.Admin.WebApp.WebServices.Types")]
    [System.SerializableAttribute()]
    public partial class EDayResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CEC.SAISE.EDayModule.EDayServiceReference.SyncExporter EDayExporterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public CEC.SAISE.EDayModule.EDayServiceReference.SyncExporter EDayExporter {
            get {
                return this.EDayExporterField;
            }
            set {
                if ((object.ReferenceEquals(this.EDayExporterField, value) != true)) {
                    this.EDayExporterField = value;
                    this.RaisePropertyChanged("EDayExporter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncExporter", Namespace="http://schemas.datacontract.org/2004/07/SAISE.Admin.WebApp.WebServices.Types")]
    [System.SerializableAttribute()]
    public partial class SyncExporter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CEC.SAISE.EDayModule.EDayServiceReference.SyncExporterStage[] StagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public CEC.SAISE.EDayModule.EDayServiceReference.SyncExporterStage[] Stages {
            get {
                return this.StagesField;
            }
            set {
                if ((object.ReferenceEquals(this.StagesField, value) != true)) {
                    this.StagesField = value;
                    this.RaisePropertyChanged("Stages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncExporterStage", Namespace="http://schemas.datacontract.org/2004/07/SAISE.Admin.WebApp.WebServices.Types")]
    [System.SerializableAttribute()]
    public partial class SyncExporterStage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatisticsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Statistics {
            get {
                return this.StatisticsField;
            }
            set {
                if ((object.ReferenceEquals(this.StatisticsField, value) != true)) {
                    this.StatisticsField = value;
                    this.RaisePropertyChanged("Statistics");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EDayServiceReference.IEDayService")]
    public interface IEDayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDayService/SyncEDayData", ReplyAction="http://tempuri.org/IEDayService/SyncEDayDataResponse")]
        CEC.SAISE.EDayModule.EDayServiceReference.EDayResponse SyncEDayData(long eDayId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDayService/SyncEDayData", ReplyAction="http://tempuri.org/IEDayService/SyncEDayDataResponse")]
        System.Threading.Tasks.Task<CEC.SAISE.EDayModule.EDayServiceReference.EDayResponse> SyncEDayDataAsync(long eDayId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDayService/GetEDayStages", ReplyAction="http://tempuri.org/IEDayService/GetEDayStagesResponse")]
        CEC.SAISE.EDayModule.EDayServiceReference.EDayResponse GetEDayStages(long eDayId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDayService/GetEDayStages", ReplyAction="http://tempuri.org/IEDayService/GetEDayStagesResponse")]
        System.Threading.Tasks.Task<CEC.SAISE.EDayModule.EDayServiceReference.EDayResponse> GetEDayStagesAsync(long eDayId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEDayServiceChannel : CEC.SAISE.EDayModule.EDayServiceReference.IEDayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDayServiceClient : System.ServiceModel.ClientBase<CEC.SAISE.EDayModule.EDayServiceReference.IEDayService>, CEC.SAISE.EDayModule.EDayServiceReference.IEDayService {
        
        public EDayServiceClient() {
        }
        
        public EDayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CEC.SAISE.EDayModule.EDayServiceReference.EDayResponse SyncEDayData(long eDayId) {
            return base.Channel.SyncEDayData(eDayId);
        }
        
        public System.Threading.Tasks.Task<CEC.SAISE.EDayModule.EDayServiceReference.EDayResponse> SyncEDayDataAsync(long eDayId) {
            return base.Channel.SyncEDayDataAsync(eDayId);
        }
        
        public CEC.SAISE.EDayModule.EDayServiceReference.EDayResponse GetEDayStages(long eDayId) {
            return base.Channel.GetEDayStages(eDayId);
        }
        
        public System.Threading.Tasks.Task<CEC.SAISE.EDayModule.EDayServiceReference.EDayResponse> GetEDayStagesAsync(long eDayId) {
            return base.Channel.GetEDayStagesAsync(eDayId);
        }
    }
}
