CREATE TABLE [schematmp].[Voter] (
    [VoterId]            BIGINT         NOT NULL,
    [NameRo]             NVARCHAR (100) NOT NULL,
    [LastNameRo]         NVARCHAR (100) NOT NULL,
    [PatronymicRo]       NVARCHAR (100) NULL,
    [LastNameRu]         NVARCHAR (100) NULL,
    [NameRu]             NVARCHAR (100) NULL,
    [PatronymicRu]       NVARCHAR (100) NULL,
    [DateOfBirth]        DATETIME       NOT NULL,
    [PlaceOfBirth]       NVARCHAR (MAX) NULL,
    [PlaceOfResidence]   NVARCHAR (MAX) NULL,
    [Gender]             INT            NOT NULL,
    [DateOfRegistration] DATETIME       NOT NULL,
    [Idnp]               BIGINT         NOT NULL,
    [DocumentNumber]     NVARCHAR (50)  NOT NULL,
    [DateOfIssue]        DATETIME       NULL,
    [DateOfExpiry]       DATETIME       NULL,
    [Status]             BIGINT         NOT NULL,
    [BatchId]            BIGINT         NULL,
    [StreetId]           BIGINT         NULL,
    [RegionId]           BIGINT         NOT NULL,
    [StreetName]         NVARCHAR (MAX) NULL,
    [StreetNumber]       BIGINT         NULL,
    [StreetSubNumber]    NVARCHAR (50)  NULL,
    [BlockNumber]        BIGINT         NULL,
    [BlockSubNumber]     NVARCHAR (50)  NULL,
    [EditUserId]         BIGINT         NOT NULL,
    [EditDate]           DATETIME       NOT NULL,
    [Version]            INT            NOT NULL,
    [ElectionListNr]     BIGINT         NULL,
    CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED ([VoterId] ASC) WITH (FILLFACTOR = 80)
);

