//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP.CEC.WebClient.RspPasswordService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="password.services.soap.rpc.framework.server.registru.md", ConfigurationName="RspPasswordService.Password")]
    public interface Password {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void changeMyPassword(string newPasswordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task changeMyPasswordAsync(string newPasswordHash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PasswordChannel : RSP.CEC.WebClient.RspPasswordService.Password, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PasswordClient : System.ServiceModel.ClientBase<RSP.CEC.WebClient.RspPasswordService.Password>, RSP.CEC.WebClient.RspPasswordService.Password {
        
        public PasswordClient() {
        }
        
        public PasswordClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PasswordClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void changeMyPassword(string newPasswordHash) {
            base.Channel.changeMyPassword(newPasswordHash);
        }
        
        public System.Threading.Tasks.Task changeMyPasswordAsync(string newPasswordHash) {
            return base.Channel.changeMyPasswordAsync(newPasswordHash);
        }
    }
}
