Use [SAISE.Admin2]

--SET IDENTITY_INSERT [dbo].[Templates] ON;
INSERT INTO [SAISE].[Templates] (TemplateId, Content, UploadDate, TemplateNameId, EditUserId, EditDate, [Version], [ParentId])
VALUES (1, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 1, -1, GETDATE(), 1, NULL),
 (2, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 2, -1, GETDATE(), 1, NULL),
 (3, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 3, -1, GETDATE(), 1, NULL),
 (4, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 4, -1, GETDATE(), 1, NULL),
 (5, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 5, -1, GETDATE(), 1, NULL),
  (6, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 6, -1, GETDATE(), 1, NULL),
  (7, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 7, -1, GETDATE(), 1, NULL),
  (8, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 8, -1, GETDATE(), 1, NULL),
  (9, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 9, -1, GETDATE(), 1, NULL),
 (10, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 10, -1, GETDATE(), 1, NULL),
 (11, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 11, -1, GETDATE(), 1, NULL),
 (12, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 12, -1, GETDATE(), 1, NULL),
 (13, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 13, -1, GETDATE(), 1, NULL),
 (14, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 14, -1, GETDATE(), 1, NULL),
 (15, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 15, -1, GETDATE(), 1, NULL),
 (16, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 16, -1, GETDATE(), 1, NULL),
 (17, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 17, -1, GETDATE(), 1, NULL),
 (18, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 18, -1, GETDATE(), 1, NULL),
 (19, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 19, -1, GETDATE(), 1, NULL),
(20, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 20, -1, GETDATE(), 1, NULL),
(21, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 21, -1, GETDATE(), 1, NULL),
 (22, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 22, -1, GETDATE(), 1, NULL),
(23, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 23, -1, GETDATE(), 1, NULL),
(24, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 24, -1, GETDATE(), 1, NULL),
(25, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 25, -1, GETDATE(), 1, NULL),
(26, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 26, -1, GETDATE(), 1, NULL),
(27, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 27, -1, GETDATE(), 1, NULL),
(28, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 28, -1, GETDATE(), 1, NULL),
(29, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 29, -1, GETDATE(), 1, NULL),
(30, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 30, -1, GETDATE(), 1, NULL),
 (31, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 31, -1, GETDATE(), 1, NULL),
 (32, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 32, -1, GETDATE(), 1, 10),
 (33, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 33, -1, GETDATE(), 1, 11),
(34, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 34, -1, GETDATE(), 1, 12),
(35, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 35, -1, GETDATE(), 1, 13),
(36, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 36, -1, GETDATE(), 1, 14),
(37, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 37, -1, GETDATE(), 1, 15),
(38, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 38, -1, GETDATE(), 1, 16),
(39, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 39, -1, GETDATE(), 1, 17),
(40, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 40, -1, GETDATE(), 1, 18),
	(41, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 41, -1, GETDATE(), 1, 19),
	(42, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 42, -1, GETDATE(), 1, 20),
	(43, '<html><head><title>Sample Template</title></head><body>Hello, World!</body></html>', GETDATE(), 43, -1, GETDATE(), 1, 21);
--SET IDENTITY_INSERT [dbo].[Templates] OFF;

