//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP.CEC.WebClient.RspClassifierService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="classifier.services.soap.rpc.framework.server.registru.md", ConfigurationName="RspClassifierService.Classifier")]
    public interface Classifier {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Items))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClassifierRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClassifierDetails))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getClassifiersNamesReturn")]
        RSP.CEC.WebClient.RspClassifierService.ClassifierDetailsRequestData getClassifiersNames(string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getClassifiersNamesReturn")]
        System.Threading.Tasks.Task<RSP.CEC.WebClient.RspClassifierService.ClassifierDetailsRequestData> getClassifiersNamesAsync(string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Items))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClassifierRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClassifierDetails))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getClassifierReturn")]
        RSP.CEC.WebClient.RspClassifierService.ClassifierRequestData getClassifier(string signature, string classifiersName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getClassifierReturn")]
        System.Threading.Tasks.Task<RSP.CEC.WebClient.RspClassifierService.ClassifierRequestData> getClassifierAsync(string signature, string classifiersName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://classifier.soap.rpc.framework.server.registru.md")]
    public partial class ClassifierDetailsRequestData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ClassifierDetails[] classifierField;
        
        private ResultData resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ClassifierDetails[] classifier {
            get {
                return this.classifierField;
            }
            set {
                this.classifierField = value;
                this.RaisePropertyChanged("classifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ResultData result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://classifier.soap.rpc.framework.server.registru.md")]
    public partial class ClassifierDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> changeIdField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> changeId {
            get {
                return this.changeIdField;
            }
            set {
                this.changeIdField = value;
                this.RaisePropertyChanged("changeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://classifier.soap.rpc.framework.server.registru.md")]
    public partial class Items : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldNamesField;
        
        private string valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fieldNames {
            get {
                return this.fieldNamesField;
            }
            set {
                this.fieldNamesField = value;
                this.RaisePropertyChanged("fieldNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://classifier.soap.rpc.framework.server.registru.md")]
    public partial class ClassifierRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Items[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Items[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://classifier.soap.rpc.framework.server.registru.md")]
    public partial class ClassifierData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> changeIdField;
        
        private ClassifierRow[] rowField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> changeId {
            get {
                return this.changeIdField;
            }
            set {
                this.changeIdField = value;
                this.RaisePropertyChanged("changeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ClassifierRow[] row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("row");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://classifier.soap.rpc.framework.server.registru.md")]
    public partial class ClassifierRequestData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ClassifierData classifierField;
        
        private ResultData resField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ClassifierData classifier {
            get {
                return this.classifierField;
            }
            set {
                this.classifierField = value;
                this.RaisePropertyChanged("classifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ResultData res {
            get {
                return this.resField;
            }
            set {
                this.resField = value;
                this.RaisePropertyChanged("res");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://classifier.soap.rpc.framework.server.registru.md")]
    public partial class ResultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorTextField;
        
        private System.Nullable<int> resultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("errorText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClassifierChannel : RSP.CEC.WebClient.RspClassifierService.Classifier, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassifierClient : System.ServiceModel.ClientBase<RSP.CEC.WebClient.RspClassifierService.Classifier>, RSP.CEC.WebClient.RspClassifierService.Classifier {
        
        public ClassifierClient() {
        }
        
        public ClassifierClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassifierClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassifierClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassifierClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RSP.CEC.WebClient.RspClassifierService.ClassifierDetailsRequestData getClassifiersNames(string signature) {
            return base.Channel.getClassifiersNames(signature);
        }
        
        public System.Threading.Tasks.Task<RSP.CEC.WebClient.RspClassifierService.ClassifierDetailsRequestData> getClassifiersNamesAsync(string signature) {
            return base.Channel.getClassifiersNamesAsync(signature);
        }
        
        public RSP.CEC.WebClient.RspClassifierService.ClassifierRequestData getClassifier(string signature, string classifiersName) {
            return base.Channel.getClassifier(signature, classifiersName);
        }
        
        public System.Threading.Tasks.Task<RSP.CEC.WebClient.RspClassifierService.ClassifierRequestData> getClassifierAsync(string signature, string classifiersName) {
            return base.Channel.getClassifierAsync(signature, classifiersName);
        }
    }
}
